/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as PreflopRouteImport } from './routes/preflop'
import { Route as RangesRouteImport } from './routes/ranges'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PreflopRoute = PreflopRouteImport.update({
  id: '/preflop',
  path: '/preflop',
  getParentRoute: () => rootRouteImport,
} as any)
const RangesRoute = RangesRouteImport.update({
  id: '/ranges',
  path: '/ranges',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/preflop': typeof PreflopRoute
  '/ranges': typeof RangesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/preflop': typeof PreflopRoute
  '/ranges': typeof RangesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/preflop': typeof PreflopRoute
  '/ranges': typeof RangesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin' | '/preflop' | '/ranges'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/preflop' | '/ranges'
  id: '__root__' | '/' | '/admin' | '/preflop' | '/ranges'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  PreflopRoute: typeof PreflopRoute
  RangesRoute: typeof RangesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preflop': {
      id: '/preflop'
      path: '/preflop'
      fullPath: '/preflop'
      preLoaderRoute: typeof PreflopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranges': {
      id: '/ranges'
      path: '/ranges'
      fullPath: '/ranges'
      preLoaderRoute: typeof RangesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  PreflopRoute: PreflopRoute,
  RangesRoute: RangesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
